### ISSUE TITLE
Migration 0007 doesn't work with separate powerdns database

### ISSUE THREAD

**Issue by blag** [allegro/django-powerdns-dnssec#142]
The bundled database router (`powerdns/routers.py`) puts all models from the powerdns app in the `powerdns` database, leading me to expect this as supported functionality.

But `Domain.owner` and `Record.owner` are both `ForeignKey`s to `settings.AUTH_USER_MODEL`, which is weird, because Django doesn't support foreign keys between databases at all.

If you try to initialize powerdns on a non-default (and empty) `powerdns` database with `python manage.py migrate powerdns --database powerdns`, the migrations error out on migrations 0007 - where the `owner` field is created:

```
Operations to perform:
  Apply all migrations: powerdns
Running migrations:
  Rendering model states... DONE
  Applying powerdns.0007_auto_20150710_0507...Traceback (most recent call last):
  File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "<settings.AUTH_USER_MODEL>" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".../lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File ".../lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File ".../lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File ".../lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File ".../lib/python3.5/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File ".../lib/python3.5/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File ".../lib/python3.5/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File ".../lib/python3.5/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File ".../lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File ".../lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File ".../lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "<setting.AUTH_USER_MODEL>" does not exist
```

However, on both the `Domain` and `Record` models there is an `account` `CharField`, which I think may have been used to tie domains and records to user accounts via usernames.

Is the separate `powerdns` database supported by this app?

**Comment by mkurek** [comment]
@blag I'm afraid that it's not supported now, but we're planning to separate powerdns app (models) from dnsaas - powerdns models will be just representation of original models from powerdns and all new stuff (especially foreign keys) will be in dnsaas app (and only from dnsaas to powerdns). Then it will work with db router.

**Comment by blag** [comment]
Okay, that's cool, thank you for all of your work on this!

If I created a PR that removed the `PowerDNSRouter` would you review and accept it if it looks good? No use in having it there if it's not supported as far as I can tell, and we can bring it back once it is eventually supported again.

**Comment by mzdeb** [comment]
Sorry, this project is not maintained anymore.
